name: windows

on:
  push:

jobs:
  cmake:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: cmake -S . -B build -DAW_ENABLE_GRAPHICS:BOOL=OFF
      - name: Build
        run: cmake --build build
      - name: Test
        run: ctest --test-dir build
